---
title: "p8105_hw6_ll3407"
output: github_document
date: "2022-11-25"
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(viridis)
library(purrr)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

set.seed(1)
```

## Problem 2
Create a city_state variable and a binary variable indicating whether the homicide is solved. 
Omit four cities.
Limit to whites and blacks.
```{r}
homicide = read_csv(file = "./data/homicide-data.csv") %>%
  janitor::clean_names() %>% 
  unite("city_state",c("city", "state"), sep = ",") %>% 
  mutate(
    resolved = recode(
       disposition, 'Closed by arrest' = 1, 'Closed without arrest' = 0, 'Open/No arrest' = 0)) %>% 
  filter(city_state != c("Dallas,TX", "Phoenix,AZ", "Kansas City,MO", "Tulsa,AL")) %>% 
  filter(victim_race == c("White","Black"))%>% 
  mutate(victim_age = as.numeric(victim_age))

```

#Fit a logistic regression model for Baltimore
```{r}
Baltimore = homicide %>% 
  filter(city_state == "Baltimore,MD") 

  fit_Baltimore = glm(resolved ~ victim_age + victim_sex + victim_race, data = Baltimore)

```

OR and 95% CIs for the resolved homicide comparing male to female in Baltimore
```{r}
OR_Baltimore = fit_Baltimore %>% broom::tidy() %>% 
  filter(term == "victim_sexMale") %>% 
  select(estimate, std.error) %>% 
  mutate(
    OR_M_to_F = exp(estimate),
    ci_lower = exp(estimate-1.96*std.error), 
    ci_upper = exp(estimate+1.96*std.error)
  )
```

GLM for each city.
OR and 95% CI for resolved homicides comparing male to female.
```{r}
nest = homicide %>% 
  select(city_state,resolved,victim_age,victim_sex,victim_race) %>% 
  mutate(race = recode(
       victim_race, 'Black' = 1, 'White' = 0)) %>% 
  mutate(sex_male = recode(
       victim_sex, 'Male' = 1, 'Female' = 0, 'Unknown' = 0)) %>% 
   mutate(sex_unknown = recode(
       victim_sex, 'Unknown' = 1, 'Female' = 0, 'Male' = 0))  %>% 
  nest(df = -city_state) 

OR = nest %>% 
  mutate(
    models = map(.x = df, ~lm(resolved ~ victim_age + sex_male + sex_unknown + race , data = .x )),
    results = map(models, broom::tidy)
  ) %>% 
  select(city_state,results) %>% 
  unnest(results) 
  
  OR_all = OR%>%
  filter(term == "sex_male") %>% 
  select(city_state, estimate, std.error) %>% 
  mutate(
    OR_M_to_F = exp(estimate),
    ci_lower = exp(estimate-1.96*std.error), 
    ci_upper = exp(estimate+1.96*std.error)
  ) %>% 
    select( -estimate, -std.error)
```

